# Generated by Django 5.0.3 on 2024-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='100 days', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
    ]
