# Generated by Django 5.0.2 on 2024-04-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vendor_authentic_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='images',
        ),
    ]
