# Generated by Django 5.0.2 on 2024-05-01 18:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
