# Generated by Django 5.0.2 on 2024-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='i am an amazing vendor', null=True),
        ),
    ]
