# Generated by Django 5.0.3 on 2024-05-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vendor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
