# Generated by Django 5.0.2 on 2024-05-12 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_address_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlist_model',
        ),
    ]
